version: '3.8'
services:
  bun:
    build: 
      context: ./sender
      dockerfile: Dockerfile.bun
    environment:
      - RUNTIME=bun
      - LEAK=${LEAK}
    depends_on: [receiver]
    mem_limit: 512m
 
  node:
    build: 
      context: ./sender
      dockerfile: Dockerfile.node
    environment:
      - RUNTIME=node
      - LEAK=${LEAK}
    depends_on: [receiver]
    mem_limit: 512m

  receiver:
    build: ./receiver
    ports:
      - "3000:3000"